/**
 * Build script to bundle @noble/secp256k1 for embedding in workers.
 *
 * This creates a self-contained IIFE that can be executed in a worker
 * without any network requests or module system dependencies.
 *
 * Usage: npx tsx scripts/bundle-ecc.ts
 */

import { build } from 'esbuild';
import { writeFileSync, mkdirSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');

async function bundleEcc(): Promise<void> {
    console.log('Bundling @noble/secp256k1 for worker embedding...');

    // Bundle @noble/secp256k1 as IIFE
    const result = await build({
        entryPoints: [resolve(projectRoot, 'node_modules/@noble/secp256k1/index.js')],
        bundle: true,
        format: 'iife',
        globalName: 'nobleSecp256k1',
        platform: 'browser',
        target: 'es2020',
        minify: true,
        write: false,
    });

    if (result.outputFiles.length === 0) {
        throw new Error('esbuild produced no output');
    }

    const bundledCode = result.outputFiles[0].text;

    // Generate TypeScript file with the bundled code as a constant
    const outputContent = `/**
 * Bundled @noble/secp256k1 for worker embedding.
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: scripts/bundle-ecc.ts
 *
 * This embeds the entire @noble/secp256k1 library as an IIFE string
 * that can be executed in a Web Worker without network requests.
 *
 * @packageDocumentation
 */

/**
 * Bundled @noble/secp256k1 library as an IIFE string.
 *
 * When executed, this creates a global \`nobleSecp256k1\` object with:
 * - sign(hash, privateKey, options): Create ECDSA signature
 * - schnorr.sign(hash, privateKey): Create Schnorr signature
 * - And other secp256k1 functions
 */
export const ECC_BUNDLE = ${JSON.stringify(bundledCode)};

/**
 * Size of the bundled code in bytes.
 */
export const ECC_BUNDLE_SIZE = ${bundledCode.length};
`;

    // Ensure output directory exists
    const outputPath = resolve(projectRoot, 'src/workers/ecc-bundle.ts');
    mkdirSync(dirname(outputPath), { recursive: true });

    // Write the output file
    writeFileSync(outputPath, outputContent, 'utf-8');

    console.log(`Bundle created: ${outputPath}`);
    console.log(`Bundle size: ${(bundledCode.length / 1024).toFixed(2)} KB`);
}

bundleEcc().catch((error) => {
    console.error('Failed to bundle ECC library:', error);
    process.exit(1);
});
